/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CargarVentana.java
 *
 * Created on 13-nov-2011, 11:22:41
 */

package Transformer;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author MaicolB
 */
public class GuardarVentana extends javax.swing.JFrame {

    public String contenido;
    /** Creates new form CargarVentana */
    public GuardarVentana(String contenido) {
        this.contenido=contenido;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elector = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        elector.setCurrentDirectory(new java.io.File("C:\\Users\\MaicolB\\Desktop"));
        elector.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        elector.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        elector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void electorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electorActionPerformed
       if(!evt.getActionCommand().equals("ApproveSelection")){
            this.setVisible(false);
        }
        if(elector.getSelectedFile().getAbsolutePath()!=null&&
                (evt.getActionCommand().equals("ApproveSelection"))){
            escribirArchivo( elector.getSelectedFile().getAbsolutePath(),contenido);
       }else{
           this.setVisible(false);
       }
       this.setVisible(false);
       JOptionPane.showMessageDialog(null, "El archivo fue guardado con exito");

    }//GEN-LAST:event_electorActionPerformed
    public  void escribirArchivo(String nombre, String contenido) {
        try {
            FileWriter fw = new FileWriter(nombre);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(contenido);
            bw.close();
            fw.close();
        } catch (IOException ioe) {
           JFrame frame=new JFrame();
            JOptionPane.showMessageDialog(frame,"Error al escribir");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser elector;
    // End of variables declaration//GEN-END:variables







}
